orgs:
  redhat-cop-dev:
    admins:
      - garethahealy
      - JaredBurck
      - oybed
      - pabrahamsson
      - sabre1041
    billing_email: andy.block@gmail.com
    company: ""
    default_repository_permission: read
    description: ""
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: ""
    members:
      - etsauer
    members_can_create_repositories: false
    name: ""
    teams:
      test-team1:
        description: ""
        maintainers:
          - sabre1041
          - pabrahamsson
        privacy: closed
        repos:
          test-repo: read
        teams:
          test-team1-subteam1:
            description: ""
            maintainers:
              - sabre1041
            privacy: closed
            repos:
              test-repo: read
